version: "3.7"

services:
  webserver:
    image: apache/airflow:2.7.2
    restart: always 
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:XUzbgroqkHzyLjbZPMeiqGOMgMEgqyeG@yamanote.proxy.rlwy.net:30045/railway
      AIRFLOW__WEBSERVER__SECRET_KEY: mysecretkey
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./airflow/config:/opt/airflow/config
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db upgrade &&
      airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com &&
      airflow webserver
      "

  scheduler:
    image: apache/airflow:2.7.2
    restart: always
    depends_on:
      - webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:XUzbgroqkHzyLjbZPMeiqGOMgMEgqyeG@yamanote.proxy.rlwy.net:30045/railway
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
      - ./airflow/config:/opt/airflow/config
    command: airflow scheduler
